version: '3'

services:
  app:
    container_name: the-shop-app
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - '8080:5000'
  
  api:
    container_name: the-shop-api
    image: nginx
    ports:
      - '8081:80'
    volumes:
      - './api:/var/www/api'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    links:
        - api-php
        - db
  
  api-php:
    container_name: the-shop-api-php
    build:
      context: .
      dockerfile: docker/api-php.dockerfile
    volumes:
      - './api:/var/www/api'
    links:
        - db

  db:
    image: mysql:5.7
    container_name: the-shop-db
    environment:
       MYSQL_ROOT_PASSWORD: the_pass
       MYSQL_DATABASE: the_shop_db
       MYSQL_USER: the_user
       MYSQL_PASSWORD: the_pass
